/* AUTO-GENERATED by 08-integration/tx-on-chain/examples/devnet/scripts/hilo_settle_stat.ts
   A REAL devnet validateStatV2 transaction proving this fixture's final score
   against TxODDS's on-chain Merkle root. Regenerate only if the fixture changes. */
export const ONCHAIN_PROOF = {
  "fixtureId": 18222446,
  "seq": 1306,
  "statKeys": [
    1,
    2
  ],
  "values": [
    3,
    1
  ],
  "claim": "final score 3-1 (home win) proven against the on-chain Merkle root",
  "program": "6pW64gN1s2uqjHkn1unFeEjAwJkPGHoppGvS715wyP2J",
  "dailyScoresPda": "FtnZq4V8mp56GUNEGGXfL1MuyT81cvoz59yeKn192HdH",
  "epochDay": 20646,
  "network": "devnet",
  "txSig": "47rYc5tphp3y3MuyCfr4KSgHLtCYZfCVknhZB57SzTPVpyWSkVUgkkvmw4kS4nGyzN2Eb49oyAUYkPJsiX4uRdhA",
  "settledAt": "2026-07-18T19:14:06.238Z"
} as const;
